git:
  depth: false
branches:
  only:
    - master
    - stable
sudo: required
language: python
python:
  - "3.6"
services:
  - docker
notifications:
  email: false
script:
  - docker-compose -f docker-compose.test.yml up --build --exit-code-from test
