git:
  depth: false
branches:
  only:
    - master
    - stable
sudo: required
language: shell
services:
  - docker
notifications:
  email: false
script:
  - docker-compose -f docker-compose.test.yml up --build --exit-code-from test
