FROM centos:8

RUN yum module -y install go-toolset postgresql && yum -y install git

ENV GOPATH=/go
ENV GO111MODULE=on

ADD go.mod  /go/src/app/
ADD go.sum  /go/src/app/

WORKDIR /go/src/app
RUN go mod download && \
    curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh \
    | sh -s -- -b $(go env GOPATH)/bin v1.22.2

ADD /base       /go/src/app/base
ADD /manager    /go/src/app/manager
ADD /listener   /go/src/app/listener
ADD /evaluator  /go/src/app/evaluator
ADD /vmaas_sync /go/src/app/vmaas_sync
ADD /docs       /go/src/app/docs
ADD /scripts    /go/src/app/scripts
ADD main.go     /go/src/app/
