version: '3.4'

services:
  patchimg:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - INSTALL_TOOLS=no
      target: runtimeimg
    image: patchman-engine-app

  db:
    container_name: db
    build:
      context: .
      dockerfile: dev/database/Dockerfile
    image: patchman-engine-db
    command: 'postgres -c config_file=/opt/app-root/src/postgresql-cfg/custom.conf'
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - 5433:5432
    env_file:
      - ./conf/database.env

  db_admin:
    container_name: db_admin
    image: patchman-engine-app
    env_file:
      - ./conf/common.env
      - ./conf/database_admin.env
    command: ./database_admin/entrypoint.sh
    depends_on:
      - db
      - patchimg
    volumes:
      - ./dev:/go/src/app/dev
      - ./dev/database/secrets:/opt/postgresql
      - ./dev/kafka/secrets:/opt/kafka
    security_opt:
      - label=disable

  db_feed:
    container_name: db_feed
    image: patchman-engine-app
    env_file:
      - ./conf/test.env
    command: go run ./scripts/feed_db.go
    depends_on:
      - db
      - patchimg
    volumes:
      - ./dev:/go/src/app/dev
      - ./dev/database/secrets:/opt/postgresql
      - ./dev/kafka/secrets:/opt/kafka
    security_opt:
      - label=disable

  zookeeper:
    image: docker.io/confluentinc/cp-zookeeper:7.0.5
    container_name: zookeeper
    env_file:
      - ./conf/zookeeper.env
    ports:
      - 2181:2181
    command: sh -c "echo 'admin.enableServer=false' >> /etc/confluent/docker/zookeeper.properties.template && /etc/confluent/docker/run"

  kafka:
    container_name: kafka
    build:
      context: .
      dockerfile: ./dev/kafka/Dockerfile
    image: patchman-engine-kafka
    env_file:
      - ./conf/kafka.env
    depends_on:
      - zookeeper
    volumes:
      - ./dev/kafka/secrets:/etc/kafka/secrets
      - ./dev/kafka:/app
    ports:
      - 29092:29092
      - 29093:29093
      - 9092:9092
      - 9093:9093
    security_opt:
      - label=disable
    # https://github.com/wurstmeister/kafka-docker/issues/389#issuecomment-875428899
    restart: always

  platform:
    container_name: platform
    image: patchman-engine-app
    env_file:
      - ./conf/platform.env
    command: ./scripts/entrypoint.sh platform
    restart: unless-stopped
    depends_on:
      - db
      - kafka
      - patchimg
    ports:
      - 9001:9001
    volumes:
      - ./:/go/src/app
    security_opt:
      - label=disable

  manager:
    container_name: manager
    image: patchman-engine-app
    env_file:
      - ./conf/common.env
      - ./conf/manager.env
    command: ./scripts/entrypoint.sh manager
    ports:
      - 8080:8080
      - 9080:9080 # metrics
    depends_on:
      - db
      - platform
      - patchimg
    volumes:
      - ./dev:/go/src/app/dev
      - ./dev/database/secrets:/opt/postgresql
      - ./dev/kafka/secrets:/opt/kafka
    security_opt:
      - label=disable

  listener:
    container_name: listener
    image: patchman-engine-app
    env_file:
      - ./conf/common.env
      - ./conf/listener.env
    command: ./scripts/entrypoint.sh listener
    ports:
      - 8081:8081
      - 9081:9081 # metrics
    depends_on:
      - db
      - platform
      - patchimg
    volumes:
      - ./dev:/go/src/app/dev
      - ./dev/database/secrets:/opt/postgresql
      - ./dev/kafka/secrets:/opt/kafka
    security_opt:
      - label=disable

  evaluator_upload:
    container_name: evaluator_upload
    image: patchman-engine-app
    env_file:
      - ./conf/common.env
      - ./conf/evaluator_common.env
      - ./conf/evaluator_upload.env
    command: ./scripts/entrypoint.sh evaluator
    ports:
      - 8082:8082
    depends_on:
      - db
      - platform
      - patchimg
    volumes:
      - ./dev:/go/src/app/dev
      - ./dev/database/secrets:/opt/postgresql
      - ./dev/kafka/secrets:/opt/kafka
    security_opt:
      - label=disable

  evaluator_recalc:
    container_name: evaluator_recalc
    image: patchman-engine-app
    env_file:
      - ./conf/common.env
      - ./conf/evaluator_common.env
      - ./conf/evaluator_recalc.env
    command: ./scripts/entrypoint.sh evaluator
    ports:
      - 8084:8084
    depends_on:
      - db
      - platform
      - patchimg
    volumes:
      - ./dev:/go/src/app/dev
      - ./dev/database/secrets:/opt/postgresql
      - ./dev/kafka/secrets:/opt/kafka
    security_opt:
      - label=disable

  vmaas_sync:
    container_name: vmaas_sync
    image: patchman-engine-app
    env_file:
      - ./conf/common.env
      - ./conf/vmaas_sync.env
    command: ./scripts/entrypoint.sh job vmaas_sync
    ports:
      - 8083:8083
    restart: on-failure
    depends_on:
      - db
      - kafka
      - platform
      - patchimg
    volumes:
      - ./dev:/go/src/app/dev
      - ./dev/database/secrets:/opt/postgresql
      - ./dev/kafka/secrets:/opt/kafka
    security_opt:
      - label=disable

  admin:
    container_name: admin
    image: patchman-engine-app
    env_file:
      - ./conf/common.env
      - ./conf/admin_api.env
    command: ./scripts/entrypoint.sh admin
    ports:
      - 8085:8085
    depends_on:
      - db
      - kafka
      - platform
      - patchimg
    volumes:
      - ./dev:/go/src/app/dev
      - ./dev/database/secrets:/opt/postgresql
      - ./dev/kafka/secrets:/opt/kafka
    security_opt:
      - label=disable

volumes:
  db-data:
