FROM centos:8

RUN rpm --import /etc/pki/rpm-gpg/RPM-GPG-KEY-centosofficial

RUN yum module -y install go-toolset && \
    yum module -y enable postgresql:12 && \
    yum install -y git postgresql diffutils

ENV GOPATH=/go
ENV GO111MODULE=on

ADD go.mod  /go/src/app/
ADD go.sum  /go/src/app/

WORKDIR /go/src/app
RUN go mod download && \
    curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh \
    | sh -s -- -b $(go env GOPATH)/bin v1.22.2

ADD /conf              /go/src/app/conf
ADD /base              /go/src/app/base
ADD /manager           /go/src/app/manager
ADD /listener          /go/src/app/listener
ADD /evaluator         /go/src/app/evaluator
ADD /vmaas_sync        /go/src/app/vmaas_sync
ADD /database_admin    /go/src/app/database_admin
ADD /docs              /go/src/app/docs
ADD /scripts           /go/src/app/scripts
ADD main.go            /go/src/app/
ADD .golangci.yml      /go/src/app/
ADD /dev               /go/src/app/dev

# Add dockerfiles for checking
ADD Dockerfile*      /go/src/app/
