
/*CREATE TABLE tag
(
    id    INT GENERATED BY DEFAULT AS IDENTITY,
    key   TEXT NOT NULL CHECK ( NOT EMPTY(formatted_key)),
    value TEXT NOT NULL,
    PRIMARY KEY (id, key, value)
);

CREATE INDEX tags_idx on tag (key, value);

GRANT SELECT, INSERT, UPDATE, DELETE ON tag to listener;
GRANT SELECT ON tag to evaluator;
GRANT SELECT ON tag to vmaas_sync;
GRANT SELECT ON tag to manager;

GRANT SELECT, USAGE ON SEQUENCE public.tag_id_seq TO evaluator;
GRANT SELECT, USAGE ON SEQUENCE public.tag_id_seq TO listener;
GRANT SELECT, USAGE ON SEQUENCE public.tag_id_seq TO vmaas_sync;
*/

CREATE TABLE system_tags
(
    tag       TEXT NOT NULL CHECK ( NOT EMPTY(tag)),
    system_id INT  NOT NULL REFERENCES system_platform ON DELETE CASCADE,
    PRIMARY KEY (system_id, tag)
);

CREATE INDEX system_tags_idx on system_tags (tag);

GRANT SELECT, INSERT, UPDATE, DELETE ON system_tags to listener;
GRANT SELECT ON system_tags to evaluator;
GRANT SELECT ON system_tags to manager;
GRANT SELECT ON system_tags to vmaas_sync;

