CREATE TABLE IF NOT EXISTS baseline
(
    id            INT                          GENERATED BY DEFAULT AS IDENTITY,
    rh_account_id INT                          NOT NULL REFERENCES rh_account (id),
    name          TEXT                         NOT NULL,
    config        JSONB,
    PRIMARY KEY (rh_account_id, id)
) PARTITION BY HASH (rh_account_id);

GRANT SELECT, UPDATE, DELETE, INSERT ON baseline TO manager;
GRANT SELECT, UPDATE, DELETE ON baseline TO listener;
GRANT SELECT, UPDATE, DELETE ON baseline TO evaluator;
GRANT SELECT, UPDATE, DELETE ON baseline TO vmaas_sync;

SELECT create_table_partitions('baseline', 16,
                               $$WITH (fillfactor = '70', autovacuum_vacuum_scale_factor = '0.05')$$);

GRANT SELECT ON ALL TABLES IN SCHEMA public TO evaluator;
GRANT SELECT ON ALL TABLES IN SCHEMA public TO listener;
GRANT SELECT ON ALL TABLES IN SCHEMA public TO manager;
GRANT SELECT ON ALL TABLES IN SCHEMA public TO vmaas_sync;

GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO evaluator;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO listener;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO vmaas_sync;

ALTER TABLE system_platform ADD COLUMN baseline_id INT;
ALTER TABLE system_platform ADD CONSTRAINT baseline_id
    FOREIGN KEY (rh_account_id, baseline_id) REFERENCES baseline (rh_account_id, id);
ALTER TABLE system_platform ADD COLUMN baseline_uptodate BOOLEAN;
