-- baseline
CREATE TABLE IF NOT EXISTS baseline
(
    id            BIGINT            GENERATED BY DEFAULT AS IDENTITY,
    rh_account_id INT               NOT NULL REFERENCES rh_account (id),
    name          TEXT              NOT NULL CHECK (not empty(name)),
    config        JSONB,
    description   TEXT              CHECK (NOT empty(description)),
    creator       TEXT              CHECK (NOT empty(creator)),
    published     TIMESTAMP WITH TIME ZONE,
    last_edited   TIMESTAMP WITH TIME ZONE,
    PRIMARY KEY (rh_account_id, id),
    UNIQUE(rh_account_id, name)
) PARTITION BY HASH (rh_account_id);

GRANT SELECT, UPDATE, DELETE, INSERT ON baseline TO manager;
GRANT SELECT, UPDATE, DELETE ON baseline TO listener;
GRANT SELECT, UPDATE, DELETE ON baseline TO evaluator;
GRANT SELECT, UPDATE, DELETE ON baseline TO vmaas_sync;

SELECT create_table_partitions('baseline', 16,
                               $$WITH (fillfactor = '70', autovacuum_vacuum_scale_factor = '0.05')$$);

ALTER TABLE system_platform ADD COLUMN baseline_id BIGINT, 
                                       baseline_uptodate BOOLEAN;
ALTER TABLE system_platform ADD CONSTRAINT baseline_id FOREIGN KEY (rh_account_id, baseline_id) REFERENCES baseline (rh_account_id, id);
