-- system_inventory
CREATE TABLE IF NOT EXISTS system_inventory
(
    id                                  BIGINT GENERATED BY DEFAULT AS IDENTITY,
    inventory_id                        UUID        NOT NULL,
    rh_account_id                       INT         NOT NULL,
    vmaas_json                          TEXT        CHECK (NOT empty(vmaas_json)),
    json_checksum                       TEXT        CHECK (NOT empty(json_checksum)),
    last_updated                        TIMESTAMPTZ NOT NULL,
    unchanged_since                     TIMESTAMPTZ NOT NULL,
    last_upload                         TIMESTAMPTZ,
    stale                               BOOLEAN     NOT NULL DEFAULT false,
    display_name                        TEXT        NOT NULL CHECK (NOT empty(display_name)),
    reporter_id                         INT,
    yum_updates                         JSONB,
    yum_checksum                        TEXT        CHECK (NOT empty(yum_checksum)),
    satellite_managed                   BOOLEAN     NOT NULL DEFAULT false,
    built_pkgcache                      BOOLEAN     NOT NULL DEFAULT false,
    arch                                TEXT        CHECK (NOT empty(arch)),
    bootc                               BOOLEAN     NOT NULL DEFAULT false,
    tags                                JSONB       NOT NULL,
    created                             TIMESTAMPTZ NOT NULL,
    workspaces                          TEXT ARRAY  CHECK (array_length(workspaces,1) > 0 or workspaces is null), -- group IDs from system_platform.groups
    stale_timestamp                     TIMESTAMPTZ NOT NULL,
    stale_warning_timestamp             TIMESTAMPTZ NOT NULL,
    culled_timestamp                    TIMESTAMPTZ NOT NULL,
    os_name                             TEXT        CHECK (NOT empty(os_name)),
    os_major                            SMALLINT,
    os_minor                            SMALLINT,
    rhsm_version                        TEXT        CHECK (NOT empty(rhsm_version)),
    subscription_manager_id             UUID,
    sap_workload                        BOOLEAN     NOT NULL DEFAULT false,
    sap_workload_sids                   TEXT ARRAY  CHECK (array_length(sap_workload_sids,1) > 0 or sap_workload_sids is null),
    ansible_workload                    BOOLEAN     NOT NULL DEFAULT false,
    ansible_workload_controller_version TEXT        CHECK (NOT empty(ansible_workload_controller_version)),
    mssql_workload                      BOOLEAN     NOT NULL DEFAULT false,
    mssql_workload_version              TEXT        CHECK (NOT empty(mssql_workload_version))
) PARTITION BY HASH (rh_account_id);

-- PARTITIONING
SELECT create_table_partitions('system_inventory', 16,
                               $$WITH (fillfactor = '70', autovacuum_vacuum_scale_factor = '0.05')
                                 TABLESPACE pg_default$$);

-- PRIVILEGES (listener has write access)
GRANT SELECT, INSERT, UPDATE ON system_inventory TO listener;
GRANT SELECT, UPDATE, DELETE ON system_inventory TO vmaas_sync; -- vmaas_sync performs system culling
GRANT SELECT, UPDATE (stale) ON system_inventory TO manager; -- manager needs to be able to update opt_out column
GRANT SELECT ON system_inventory TO evaluator;
SELECT grant_table_partitions('SELECT', 'system_inventory', 'evaluator');
SELECT grant_table_partitions('SELECT', 'system_inventory', 'listener');
SELECT grant_table_partitions('SELECT', 'system_inventory', 'manager');
SELECT grant_table_partitions('SELECT', 'system_inventory', 'vmaas_sync');
GRANT SELECT, USAGE ON SEQUENCE system_inventory_id_seq TO evaluator;
GRANT SELECT, USAGE ON SEQUENCE system_inventory_id_seq TO listener;
GRANT SELECT, USAGE ON SEQUENCE system_inventory_id_seq TO vmaas_sync;

-- LOAD DATA
CREATE OR REPLACE FUNCTION safe_to_int(input_text TEXT)
RETURNS SMALLINT AS $$
BEGIN
  RETURN input_text::SMALLINT;
EXCEPTION WHEN OTHERS THEN
  RETURN NULL;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION safe_to_uuid(input_text TEXT)
RETURNS UUID AS $$
BEGIN
  RETURN input_text::UUID;
EXCEPTION WHEN OTHERS THEN
  RETURN NULL;
END;
$$ LANGUAGE plpgsql;

INSERT INTO system_inventory SELECT
    sp.id,
    sp.inventory_id,
    sp.rh_account_id,
    sp.vmaas_json,
    sp.json_checksum,
    sp.last_updated,
    sp.unchanged_since,
    sp.last_upload,
    sp.stale,
    COALESCE(sp.display_name, ih.display_name),
    sp.reporter_id,
    sp.yum_updates,
    sp.yum_checksum,
    sp.satellite_managed,
    sp.built_pkgcache,
    sp.arch,
    sp.bootc,
    ih.tags,
    ih.created,
    ARRAY(SELECT jsonb_array_elements(ih.groups)->>'id') AS workspaces,
    COALESCE(ih.stale_timestamp, sp.stale_timestamp),
    COALESCE(ih.stale_warning_timestamp, sp.stale_warning_timestamp),
    COALESCE(ih.culled_timestamp, sp.culled_timestamp),
    ih.system_profile->'operating_system'->>'name' AS os_name,
    safe_to_int(ih.system_profile->'operating_system'->>'major') AS os_major,
    safe_to_int(ih.system_profile->'operating_system'->>'minor') AS os_minor,
    ih.system_profile->'rhsm'->>'version' AS rhsm_version,
    safe_to_uuid(ih.system_profile->>'owner_id') AS subscription_manager_id,
    COALESCE((ih.system_profile->'workloads'->'sap'->>'sap_system')::BOOLEAN, false) AS sap_workload,
    ARRAY(SELECT jsonb_array_elements_text(ih.system_profile->'workloads'->'sap'->'sids')) AS sap_workload_sids,
    COALESCE(LENGTH(ih.system_profile->'workloads'->>'ansible') > 2, false) AS ansible_workload,
    ih.system_profile->'workloads'->'ansible'->>'controller_version' AS ansible_workload_controller_version,
    COALESCE(LENGTH(ih.system_profile->'workloads'->>'mssql') > 2, false) AS mssql_workload,
    ih.system_profile->'workloads'->'mssql'->>'version' AS mssql_workload_version
FROM inventory.hosts ih JOIN system_platform sp ON ih.id = sp.inventory_id
WHERE sp.stale = false;

SELECT setval('system_inventory_id_seq', (SELECT MAX(id) FROM system_inventory));

DROP FUNCTION safe_to_int;
DROP FUNCTION safe_to_uuid;

-- TRIGGERS
SELECT create_table_partition_triggers('system_inventory_set_last_updated',
                                       $$BEFORE INSERT OR UPDATE$$,
                                       'system_inventory',
                                       $$FOR EACH ROW EXECUTE PROCEDURE set_last_updated()$$);

SELECT create_table_partition_triggers('system_inventory_check_unchanged',
                                       $$BEFORE INSERT OR UPDATE$$,
                                       'system_inventory',
                                       $$FOR EACH ROW EXECUTE PROCEDURE check_unchanged()$$);

SELECT create_table_partition_triggers('system_inventory_on_update',
                                       $$AFTER UPDATE$$,
                                       'system_inventory',
                                       $$FOR EACH ROW EXECUTE PROCEDURE on_system_update()$$);

-- CONSTRAINTS
ALTER TABLE IF EXISTS system_inventory
ADD PRIMARY KEY (rh_account_id, id),
ADD FOREIGN KEY (rh_account_id) REFERENCES rh_account (id),
ADD FOREIGN KEY (reporter_id) REFERENCES reporter (id),
ADD UNIQUE (rh_account_id, inventory_id);

-- INDEXES
CREATE INDEX IF NOT EXISTS system_inventory_inventory_id_idx ON system_inventory (inventory_id);
CREATE INDEX IF NOT EXISTS system_inventory_tags_index ON system_inventory USING GIN (tags JSONB_PATH_OPS);
CREATE INDEX IF NOT EXISTS system_inventory_stale_timestamp_index ON system_inventory (stale_timestamp);
CREATE INDEX IF NOT EXISTS system_inventory_workspaces_index ON system_inventory USING GIN (workspaces);

-- UPDATE FKEYS
ALTER TABLE IF EXISTS system_repo
DROP CONSTRAINT system_platform_id,
ADD CONSTRAINT system_inventory_id
    FOREIGN KEY (rh_account_id, system_id)
    REFERENCES system_inventory (rh_account_id, id);

ALTER TABLE IF EXISTS system_advisories
DROP CONSTRAINT system_platform_id,
ADD CONSTRAINT system_inventory_id
    FOREIGN KEY (rh_account_id, system_id)
    REFERENCES system_inventory (rh_account_id, id);

ALTER TABLE IF EXISTS system_package2
DROP CONSTRAINT system_package2_rh_account_id_system_id_fkey,
ADD CONSTRAINT system_inventory_id
    FOREIGN KEY (rh_account_id, system_id)
    REFERENCES system_inventory (rh_account_id, id);



-- system_patch
CREATE TABLE IF NOT EXISTS system_patch
(
    system_id                            BIGINT      NOT NULL,
    rh_account_id                        INT         NOT NULL,
    last_evaluation                      TIMESTAMPTZ,
    installable_advisory_count_cache     INT         NOT NULL DEFAULT 0,
    installable_advisory_enh_count_cache INT         NOT NULL DEFAULT 0,
    installable_advisory_bug_count_cache INT         NOT NULL DEFAULT 0,
    installable_advisory_sec_count_cache INT         NOT NULL DEFAULT 0,
    packages_installed                   INT         NOT NULL DEFAULT 0,
    packages_installable                 INT         NOT NULL DEFAULT 0,
    packages_applicable                  INT         NOT NULL DEFAULT 0,
    third_party                          BOOLEAN     NOT NULL DEFAULT false,
    applicable_advisory_count_cache      INT         NOT NULL DEFAULT 0,
    applicable_advisory_enh_count_cache  INT         NOT NULL DEFAULT 0,
    applicable_advisory_bug_count_cache  INT         NOT NULL DEFAULT 0,
    applicable_advisory_sec_count_cache  INT         NOT NULL DEFAULT 0,
    template_id                          BIGINT
) PARTITION BY HASH (rh_account_id);

-- PARTITIONING
SELECT create_table_partitions('system_patch', 16,
                               $$WITH (fillfactor = '70', autovacuum_vacuum_scale_factor = '0.05')
                                 TABLESPACE pg_default$$);

-- PRIVILEGES (evaluator has write access)
GRANT SELECT, UPDATE ON system_patch TO evaluator;
GRANT SELECT, UPDATE (installable_advisory_count_cache,
              installable_advisory_enh_count_cache,
              installable_advisory_bug_count_cache,
              installable_advisory_sec_count_cache,
              applicable_advisory_count_cache,
              applicable_advisory_enh_count_cache,
              applicable_advisory_bug_count_cache,
              applicable_advisory_sec_count_cache) ON system_patch TO manager;
GRANT SELECT, UPDATE, DELETE ON system_patch to vmaas_sync; -- vmaas_sync performs system culling
SELECT grant_table_partitions('SELECT', 'system_patch', 'evaluator');
SELECT grant_table_partitions('SELECT', 'system_patch', 'listener');
SELECT grant_table_partitions('SELECT', 'system_patch', 'manager');
SELECT grant_table_partitions('SELECT', 'system_patch', 'vmaas_sync');

INSERT INTO system_patch SELECT
    id,
    rh_account_id,
    last_evaluation,
    installable_advisory_count_cache,
    installable_advisory_enh_count_cache,
    installable_advisory_bug_count_cache,
    installable_advisory_sec_count_cache,
    packages_installed,
    packages_installable,
    packages_applicable,
    third_party,
    applicable_advisory_count_cache,
    applicable_advisory_enh_count_cache,
    applicable_advisory_bug_count_cache,
    applicable_advisory_sec_count_cache,
    template_id
FROM system_platform sp
WHERE sp.stale = false;

-- CONSTRAINTS
ALTER TABLE IF EXISTS system_patch 
ADD PRIMARY KEY (rh_account_id, system_id),
ADD FOREIGN KEY (rh_account_id, template_id) REFERENCES template (rh_account_id, id),
ADD FOREIGN KEY (system_id, rh_account_id) REFERENCES system_inventory (id, rh_account_id);
