FROM centos/postgresql-10-centos7

ENV POSTGRESQL_DATABASE 'spm'
ENV POSTGRESQL_USER 'admin'
ENV POSTGRESQL_PASSWORD 'passwd'
ENV POSTGRESQL_MAX_CONNECTIONS '500'

#ADD database/schema.sql ${CONTAINER_SCRIPTS_PATH}/start/
#ADD database/schema/ve_db_user_create_postgresql.sql ${CONTAINER_SCRIPTS_PATH}/start/
#ADD database/schema/init_schema.sh ${CONTAINER_SCRIPTS_PATH}/start/
