openapi: "3.0.0"

info:
  version: "1"
  title: "SPM Prototype in Python"

paths:
  /host/{id}:
    get:
      operationId: handler.get_host
      responses:
        200:
          description: "System created"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PackageList'
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer

components:
  schemas:
    PackageList:
      type: object
      properties:
        package_list:
          type: array
          items:
            type: string
