openapi: "3.0.0"

info:
  version: "1"
  title: "SPM Prototype in Python"

paths:
  /create_host:
    post:
      operationId: handler.create_host
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateHostBody'
      responses:
        200:
          description: "System created"
          content:
            application/json:
              schema:
                type: object
                
  /update_host:
    post:
      operationId: handler.update_host
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateHostBody'
      responses:
        200:
          description: "Host updated"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UpdateHostResponse"
                
components:
  schemas:
    CreateHostBody:
      type: object
      properties:
        name: 
          type: string
        content:
          type: object
          properties: 
            pkgs:
              type: array
              items:
                type: string
      
    UpdateHostBody:
      type: object
      additionalProperties:
        type: string
        example: 'pkg_name'
      
    UpdateHostResponse:
      type: object
      properties:
        updated_systems:
          type: integer
                
          
