apiVersion: v1
kind: Template
metadata:
  name: patchman-engine-listener

parameters:
  - name: IMAGE_NAMESPACE
    displayName: Image namespace
  - name: IMAGE_TAG
    displayName: Image tag
    value: latest
  - name: KAFKA_ADDRESS
  - name: INVENTORY_ADDRESS
  - name: VMAAS_ADDRESS

objects:
  - apiVersion: v1
    kind: DeploymentConfig
    metadata:
      labels: { app: patchman-engine }
      name: patchman-engine-listener
    spec:
      replicas: 1
      selector:
        app: patchman-engine
        deploymentconfig: patchman-engine-listener
      template:
        metadata:
          labels:
            app: patchman-engine
            deploymentconfig: patchman-engine-listener
          name: patchman-engine-listener
        spec:
          containers:
            - image: ${IMAGE_NAMESPACE}/patchman-engine-app:${IMAGE_TAG}
              imagePullPolicy: Always
              name: patchman-engine-listener
              command: [ ./listener/entrypoint.sh ]
              resources:
                limits: { cpu: 500m,  memory: 512Mi }
                requests: { cpu: 200m, memory: 512Mi }
              livenessProbe:
                httpGet: { path: /metrics, port: 8081, scheme: HTTP }
              readinessProbe:
                httpGet: { path: /metrics, port: 8081, scheme: HTTP }
              env:
                - { name: LOG_LEVEL, value: debug }
                - { name: LOG_STYLE, value: plain }
                - { name: GIN_MODE, value: release }

                - { name: KAFKA_ADDRESS, value: "${KAFKA_ADDRESS}" }
                - { name: KAFKA_GROUP, value: patchman }
                - { name: UPLOAD_TOPIC, value: platform.upload.available }
                - { name: EVENTS_TOPIC, value: platform.inventory.events }

                - { name: INVENTORY_ADDRESS, value: "${INVENTORY_ADDRESS}" }
                - { name: VMAAS_ADDRESS, value: "${VMAAS_ADDRESS}" }

                - { name: DB_TYPE, value: postgres }
                - { name: DB_HOST, value: patchman-engine-database }
                - { name: DB_PORT, value: "5432" }
                - { name: DB_NAME, value: patchman }
                - { name: DB_USER, value: listener }
                - name: DB_PASSWD
                  valueFrom:
                    secretKeyRef:
                      name:  patchman-engine-database-passwords
                      key: listener-database-password

          dnsPolicy: ClusterFirst
          restartPolicy: Always
      triggers:
        - type: ConfigChange
        - imageChangeParams:
            automatic: true
            containerNames:
              - patchman-engine-listener
            from:
              kind: ImageStreamTag
              name: patchman-engine-app:${IMAGE_TAG}
              namespace: ${IMAGE_NAMESPACE}
          type: ImageChange

  - apiVersion: v1
    kind: Service
    metadata:
      labels:
        app: patchman-engine
      name: patchman-engine-listener
    spec:
      type: ClusterIP
      ports:
        - name: 8081-tcp
          port: 8081
          protocol: TCP
          targetPort: 8081
      selector:
        app: patchman-engine
        deploymentconfig: patchman-engine-listener

