{
 "title": "patchman-engine",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "interval",
    "query": "1m,5m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   { "name": "evaluator", "query": ".*, upload.*, recalc.*" },
   { "name": "event", "label": "event", "query": "upload, delete, .*" },
   { "name": "datasource", "label": "datasource", "query": "prometheus" },
   { "name": "rds_datasource", "label": "rds_datasource", "query": "prometheus" },
   { "name": "namespace", "query": ".*, -prod, -stage, -perf" },
   {
    "name": "latency_endpoint",
    "query": {
     "query": "patchman_engine_manager_request_durations_bucket"
    }
   }
  ]
 },
 "panels": [
  { "title": "Current values", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Manager requests",
   "type": "stat",
   "description": "The number of Manager requests.",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "delta" ] } },
   "targets": [
    {
     "expr": "sum(increase(patchman_engine_requests_total{job=~\"patchman.*-manager\"}[$__range]))"
    }
   ]
  },
  {
   "title": "Manager 2xx ratio",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(patchman_engine_requests_total{job=~\"patchman.*-manager\", code=~\"2.*\"}[$__range])) / sum(increase(patchman_engine_requests_total{job=~\"patchman.*-manager\"}[$__range]))"
    }
   ]
  },
  {
   "title": "Manager restarts",
   "type": "stat",
   "description": "The number of Manager restarts.",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "delta" ] } },
   "targets": [
    {
     "expr": "max(sum(kube_pod_container_status_restarts_total{pod=~\"patchman.*-manager.*\"}))"
    }
   ]
  },
  {
   "title": "Listener restarts",
   "type": "stat",
   "description": "The number of Listener restarts.",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "delta" ] } },
   "targets": [
    {
     "expr": "max(sum(kube_pod_container_status_restarts_total{pod=~\"patchman.*-listener.*\"}))"
    }
   ]
  },
  {
   "title": "Evaluator-upload restarts",
   "type": "stat",
   "description": "The number of Evaluator-upload restarts.",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "delta" ] } },
   "targets": [
    {
     "expr": "max(sum(kube_pod_container_status_restarts_total{pod=~\"patchman.*-evaluator-upload.*\"}))"
    }
   ]
  },
  {
   "title": "Evaluator-recalc restarts",
   "type": "stat",
   "description": "The number of Evaluator-recalc restarts.",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "delta" ] } },
   "targets": [
    {
     "expr": "max(sum(kube_pod_container_status_restarts_total{pod=~\"patchman.*-evaluator-recalc.*\"}))"
    }
   ]
  },
  {
   "title": "VMaaS-sync restarts",
   "type": "stat",
   "description": "The number of VMaaS-sync restarts.",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "delta" ] } },
   "targets": [
    {
     "expr": "max(kube_pod_container_status_restarts_total{pod=~\"patchman.*-vmaas-sync.*\"})"
    }
   ]
  },
  {
   "title": "Latency uptime (30d)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg_over_time(service:sli:latency_gt_2000:pctl10rate5m{exported_service=\"patch\"}[30d])"
    }
   ]
  },
  {
   "title": "Manager 5xx ratio",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(patchman_engine_requests_total{job=~\"patchman.*-manager\", code=~\"5.*\"}[$__range])) / sum(increase(patchman_engine_requests_total{job=~\"patchman.*-manager\"}[$__range]))"
    }
   ]
  },
  {
   "title": "Manager 4xx ratio",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(patchman_engine_requests_total{job=~\"patchman.*-manager\", code=~\"4.*\"}[$__range])) / sum(increase(patchman_engine_requests_total{job=~\"patchman.*-manager\"}[$__range]))"
    }
   ]
  },
  {
   "title": "Version",
   "type": "stat",
   "description": "Build version running in this environment.",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(patchman_engine_core_info{namespace=~\"patchman-engine$namespace\"}) by (version)"
    }
   ]
  },
  {
   "title": "Deployed versions",
   "type": "stat",
   "description": "This is to ensure that all components are running in the same version.",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(sum(patchman_engine_core_info{namespace=~\"patchman-engine$namespace\"}) by (version))"
    }
   ]
  },
  {
   "title": "Evaluated uploads",
   "type": "stat",
   "description": "Systems evaluated using component \"patchman.*-evaluator-upload\".",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "delta" ] } },
   "targets": [
    {
     "expr": "sum(patchman_engine_evaluator_evaluation{pod=~\"patchman.*-evaluator-upload-.*\", type=\"success\"})"
    }
   ]
  },
  {
   "title": "Evaluated recalcs",
   "type": "stat",
   "description": "Systems evaluated using component \"patchman.*-evaluator-recalc\".",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "delta" ] } },
   "targets": [
    {
     "expr": "sum(patchman_engine_evaluator_evaluation{pod=~\"patchman.*-evaluator-recalc-.*\", type=\"success\"})"
    }
   ]
  },
  {
   "title": "Listener messages",
   "type": "stat",
   "description": "The number of messages processed using Listener.",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "delta" ] } },
   "targets": [
    {
     "expr": "sum(patchman_engine_listener_kafka_message_received{event=~\"$event\"})"
    }
   ]
  },
  {
   "title": "Latency uptime",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg_over_time(service:sli:latency_gt_2000:pctl10rate5m{exported_service=\"patch\"}[$__range])"
    }
   ]
  },
  { "title": "Golden signals", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Manager traffic",
   "type": "timeseries",
   "description": "The number of requests per second in Manager.",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(patchman_engine_requests_total{}[$interval])) by (code)",
     "legendFormat": "All {{code}}"
    },
    {
     "expr": "sum(rate(patchman_engine_manager_request_durations_count{}[$interval])) by (exported_endpoint)",
     "legendFormat": "{{exported_endpoint}}"
    }
   ]
  },
  {
   "title": "Manager latency",
   "type": "timeseries",
   "description": "Calculation of latency for Manager.",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "1000 * sum(rate(patchman_engine_request_duration_seconds_sum{}[$interval])) / sum(rate(patchman_engine_request_duration_seconds_count{}[$interval]))",
     "legendFormat": "Mean"
    },
    {
     "expr": "1000 * sum(rate(patchman_engine_manager_request_durations_sum{}[$interval])) by (exported_endpoint) / sum(rate(patchman_engine_manager_request_durations_count{}[$interval])) by (exported_endpoint)",
     "legendFormat": "{{exported_endpoint}}"
    }
   ]
  },
  {
   "title": "CPU consumed",
   "type": "timeseries",
   "description": "The percentage of CPU usage for each container.",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{container=~\"patchman-.*\", namespace=~\"patchman-engine$namespace\"}[$interval])) by (container)/ sum(kube_pod_container_resource_limits{container=~\"patchman-.*\", namespace=~\"patchman-engine$namespace\", resource=\"cpu\"}) by (container)",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "Memory consumed",
   "type": "timeseries",
   "description": "The percentage of memory usage for each container.",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{container=~\"patchman-.*\", namespace=~\"patchman-engine$namespace\"}) by (container) / sum(kube_pod_container_resource_limits{container=~\"patchman-.*\", namespace=~\"patchman-engine$namespace\", resource=\"memory\"}) by (container)",
     "legendFormat": "{{container}}"
    }
   ]
  },
  { "title": "Restarts & Kafka", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "Containers restarts",
   "type": "timeseries",
   "description": "The number of restarts for each container.",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_restarts_total{pod=~\"patchman.*-.*\", namespace=~\"patchman-engine$namespace\"}) by (container)",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "Kafka consumer lag",
   "type": "timeseries",
   "description": "Kafka consumer lag by each topic.",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "aws_kafka_sum_offset_lag_sum{consumer_group=\"patchman\"}",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  { "title": "Manager", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  {
   "title": "Manager API latency per endpoint",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(increase(patchman_engine_manager_request_durations_bucket{le=\"2\"}[$__range])) by (exported_endpoint) / sum(increase(patchman_engine_manager_request_durations_bucket{le=\"+Inf\"}[$__range])) by (exported_endpoint)",
     "legendFormat": "{{exported_endpoint}}"
    }
   ]
  },
  {
   "title": "Manager API Latency - $latency_endpoint (select on top)",
   "type": "heatmap",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 28 },
   "targets": [
    {
     "expr": "sum(increase(patchman_engine_manager_request_durations_bucket{exported_endpoint=\"$latency_endpoint\"}[5m])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Advisory detail cache",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(patchman_engine_manager_advisory_detail_cache{type=\"hit\"})/sum(patchman_engine_manager_advisory_detail_cache)",
     "legendFormat": "hit ratio"
    },
    {
     "expr": "sum(patchman_engine_manager_advisory_detail_cache_size)",
     "legendFormat": "size"
    }
   ]
  },
  {
   "title": "Package account data usage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(patchman_engine_manager_package_account_data_cache)",
     "legendFormat": "items"
    },
    {
     "expr": "sum(patchman_engine_manager_package_account_data_cache{type=\"hit\"})/sum(patchman_engine_manager_package_account_data_cache)",
     "legendFormat": "hit ratio"
    }
   ]
  },
  { "title": "Listener", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 46 } },
  {
   "title": "Processed messages by reporter",
   "type": "timeseries",
   "description": "The number of messages per second received by each reporter in Listener.",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(patchman_engine_listener_received_from_reporter[$interval])) by (reporter)",
     "legendFormat": "{{reporter}}"
    }
   ]
  },
  {
   "title": "Processed messages by result",
   "type": "timeseries",
   "description": "The number of messages per second received by result in Listener.",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(patchman_engine_listener_kafka_message_received{event=~\"$event\"}[$interval])) by (type)",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Message processing part duration",
   "type": "timeseries",
   "description": "The duration of particular part in Listener.",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(patchman_engine_listener_kafka_message_part_duration_seconds_bucket{job=~\"patchman.*-listener.*\"}[$interval])) by (part, le))",
     "legendFormat": "{{type}}"
    }
   ]
  },
  { "title": "Evaluator", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 59 } },
  {
   "title": "Upload - evaluation delay",
   "type": "timeseries",
   "description": "The delay from upload to evaluation.",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(rate(patchman_engine_evaluator_upload_evaluation_delay_seconds_sum{job=~\"patchman.*-evaluator-upload\"}[5m]))",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "delay",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "System evaluations",
   "type": "timeseries",
   "description": "The number of systems per second evaluated by type.",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(patchman_engine_evaluator_evaluation{pod=~\"patchman.*-evaluator-$evaluator\"}[$interval])) by (type)",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "System evaluations by pod - recalc",
   "type": "timeseries",
   "description": "The number of evaluations per second evaluated by \"patchman.*-evaluator-recalc\".",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(patchman_engine_evaluator_evaluation{pod=~\"patchman.*-evaluator-recalc.*\"}[$interval])) by (pod)",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "System evaluations by pod - upload",
   "type": "timeseries",
   "description": "The number of evaluations per second evaluated by \"patchman.*-evaluator-upload\".",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(patchman_engine_evaluator_evaluation{pod=~\"patchman.*-evaluator-upload.*\"}[$interval])) by (pod)",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "System evaluation duration",
   "type": "timeseries",
   "description": "The duration of system evaluation.",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 72 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(rate(patchman_engine_evaluator_evaluation_duration_seconds_sum{job=~\"patchman.*-evaluator-$evaluator\"}[$interval]))",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "delay",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Evaluation part duration median",
   "type": "timeseries",
   "description": "The median value of duration of particular evaluation part.",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 72 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(patchman_engine_evaluator_evaluation_part_duration_seconds_bucket{job=~\"patchman.*-evaluator-$evaluator\"}[$interval])) by (part, le))",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{part}}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Two evaluations interval",
   "type": "timeseries",
   "description": "The time interval between two evaluations.",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 78 },
   "fieldConfig": { "defaults": { "unit": "h" } },
   "targets": [
    {
     "expr": "avg(rate(patchman_engine_evaluator_two_evaluations_interval_hours_sum{job=~\"patchman.*-evaluator-$evaluator\"}[$interval]))",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "delay",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "System evaluations - patched/unpatched",
   "type": "timeseries",
   "description": "The number of system evaluations by type.",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 78 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(patchman_engine_evaluator_updates{pod=~\"patchman.*-evaluator-$evaluator\"}[$interval])) by (type)",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Package cache hit ratio",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 84 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(patchman_engine_evaluator_package_cache{type=\"hit\"}) by (by)/sum(patchman_engine_evaluator_package_cache) by (by)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Package cache size",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 84 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(patchman_engine_evaluator_package_cache_size) by (container)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "VMaaS cache hit ratio",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 90 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(patchman_engine_evaluator_vmaas_cache{type=\"hit\"})/sum(patchman_engine_evaluator_vmaas_cache)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "VMaaS cache size",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 90 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(patchman_engine_evaluator_vmaas_cache_size) by (container)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Jobs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 96 } },
  {
   "title": "Package refresh part duration median",
   "type": "timeseries",
   "description": "The median value of duration of particular evaluation part.",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 97 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(patchman_engine_caches_package_refresh_part_duration_seconds_bucket[$interval])) by (part, le))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Vmaas sync - external services",
   "type": "timeseries",
   "description": "The number of external services calls and their result.",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 97 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(increase(patchman_engine_vmaas_sync_vmaas_call{}[$interval])) by (type)",
     "legendFormat": "VMaaS Sync - {{type}}"
    },
    {
     "expr": "sum(increase(patchman_engine_manager_dependency_call{name=\"rbac\"}[$interval])) by (name, status)",
     "legendFormat": "{{name}} - {{status}}"
    }
   ]
  },
  {
   "title": "System culling",
   "type": "timeseries",
   "description": "The number of culled systems per second which were deleted.",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 103 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(increase(patchman_engine_vmaas_sync_deleted_culled_systems{}[$interval]))",
     "legendFormat": "deleted systems"
    },
    {
     "expr": "sum(increase(patchman_engine_vmaas_sync_stale_systems_marked{}[$interval]))",
     "legendFormat": "marked stale systems"
    }
   ]
  },
  { "title": "Database", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 109 } },
  {
   "title": "Database items - systems",
   "type": "timeseries",
   "description": "The number of stored systems by their last upload.",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 110 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "avg(sum(patchman_engine_vmaas_sync_systems{last_upload=~\"last.*|all\"}) by (last_upload, pod)) by (last_upload)",
     "legendFormat": "{{last_upload}}"
    },
    {
     "expr": "avg(sum(patchman_engine_vmaas_sync_systems{last_upload=~\"last.*|all\"}) by (last_upload, pod)) by (last_upload) - avg(sum(label_replace(patchman_engine_vmaas_sync_systems_count_by_type{type=~\"last.*|all\"}, \"last_upload\", \"$1\", \"type\", \"(.*)\")) by (last_upload, pod)) by (last_upload)",
     "legendFormat": "{{last_upload}} - delta (patch - inv): "
    }
   ]
  },
  {
   "title": "Database items - advisories",
   "type": "timeseries",
   "description": "The number of advisories stored by each type and total.",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 110 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "avg(sum(patchman_engine_vmaas_sync_advisories{}) by (type, pod)) by (type)",
     "legendFormat": "{{type}}"
    },
    {
     "expr": "avg(sum(patchman_engine_vmaas_sync_advisories{}) by (pod))",
     "legendFormat": "all"
    }
   ]
  },
  {
   "title": "Database items - System inventory data",
   "type": "timeseries",
   "description": "The number of inventory hosts by type.",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 116 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "avg(sum(patchman_engine_vmaas_sync_tags_count_by_type) by (type, pod)) by (type)",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Database items - packages",
   "type": "timeseries",
   "description": "The number of stored packages and packages names.",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 116 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "avg(sum(patchman_engine_vmaas_sync_packages{}) by (pod))",
     "legendFormat": "packages"
    },
    {
     "expr": "avg(sum(patchman_engine_vmaas_sync_package_names{}) by (pod))",
     "legendFormat": "package_names"
    }
   ]
  },
  {
   "title": "Database size",
   "type": "timeseries",
   "description": "The current database size and tables sizes.",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 122 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "avg(sum(patchman_engine_vmaas_sync_database_size_bytes{}) by (table, pod)) by (table)",
     "legendFormat": "{{table}}"
    },
    {
     "expr": "avg(sum(patchman_engine_vmaas_sync_database_size_bytes{table=~\"public.system_advisories_.*\"}) by (pod))",
     "legendFormat": "system_advisories_sum"
    },
    {
     "expr": "avg(sum(patchman_engine_vmaas_sync_database_size_bytes{table=~\"public.system_package2_.*\"}) by (pod))",
     "legendFormat": "system_package_sum"
    },
    {
     "expr": "avg(sum(patchman_engine_vmaas_sync_database_size_bytes{table=~\"public.system_inventory_.*\"}) by (pod))",
     "legendFormat": "system_inventory_sum"
    },
    {
     "expr": "avg(sum(patchman_engine_vmaas_sync_database_size_bytes{table=~\"public.system_patch_.*\"}) by (pod))",
     "legendFormat": "system_patch_sum"
    },
    {
     "expr": "avg(sum(patchman_engine_vmaas_sync_database_size_bytes{table=~\"public.template_.*\"}) by (pod))",
     "legendFormat": "template_sum"
    }
   ]
  },
  {
   "title": "Database processes",
   "type": "timeseries",
   "description": "The number of database processes by their use.",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 122 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "avg(sum(patchman_engine_vmaas_sync_database_processes{}) by (usename, pod)) by (usename)",
     "legendFormat": "{{usename}}"
    }
   ]
  },
  { "title": "Database (RDS metrics)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 128 } },
  {
   "title": "RDS - data capacity usage",
   "type": "timeseries",
   "description": "The percentage of available files in use by mount point.",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 129 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(rdsosmetrics_fileSys_usedPercent{exported_instance=~\"patchman-.*\"}) by (mount_point)",
     "legendFormat": "{{mount_point}}"
    }
   ]
  },
  {
   "title": "RDS - CPU usage",
   "type": "timeseries",
   "description": "The percentage of CPU used by the process.",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 129 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(label_replace(rdsosmetrics_processList_cpuUsedPc{exported_instance=~\"patchman-.*\"}, \"db_user\", \"$1\", \"name\", \"postgres: ([^ ]+) .+\")) by (db_user)",
     "legendFormat": "{{db_user}}"
    },
    {
     "expr": "sum(rdsosmetrics_processList_cpuUsedPc{exported_instance=~\"patchman-.*\"})",
     "legendFormat": "sum"
    }
   ]
  },
  {
   "title": "RDS - memory",
   "type": "timeseries",
   "description": "The total memory, free memory and dirty memory.",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 135 },
   "fieldConfig": { "defaults": { "unit": "deckbytes" } },
   "targets": [
    {
     "expr": "sum(rdsosmetrics_memory_total{exported_instance=~\"patchman-.*\"})",
     "legendFormat": "total memory"
    },
    {
     "expr": "sum(rdsosmetrics_memory_free{exported_instance=~\"patchman-.*\"})",
     "legendFormat": "free memory"
    },
    {
     "expr": "sum(rdsosmetrics_memory_dirty{exported_instance=~\"patchman-.*\"})",
     "legendFormat": "dirty memory"
    },
    {
     "expr": "sum(rdsosmetrics_memory_active{exported_instance=\"patchman-prod\"})",
     "legendFormat": "active memory"
    }
   ]
  },
  {
   "title": "RDS - load average minute",
   "type": "timeseries",
   "description": "The number of processes requesting CPU time over the last 1/5/15 minutes.",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 135 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rdsosmetrics_loadAverageMinute_one{exported_instance=~\"patchman-.*\"})",
     "legendFormat": "Load Avg 1 min"
    },
    {
     "expr": "sum(rdsosmetrics_loadAverageMinute_five{exported_instance=~\"patchman-.*\"})",
     "legendFormat": "Load Avg 5 min"
    },
    {
     "expr": "sum(rdsosmetrics_loadAverageMinute_fifteen{exported_instance=~\"patchman-.*\"})",
     "legendFormat": "Load Avg 15 min"
    }
   ]
  }
 ]
}