name: ci_deploy

on: [push]
# TODO: This is target trigger, just testing
#  pull_request:
#    branches:
#      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: '3.x'
      - name: Install ocdeployer
        run: pip install ocdeployer
      - name: Deploy
        run: ocdeployer deploy -t openshift patchman-engine-ci -s build,deploy --secrets-local-dir openshift/secrets