name: Create release
on:
  push:
    branches:
      - master
    paths:
      - "VERSION"

permissions:
  contents: write

jobs:
  tag-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Read tag from version file
        id: version
        run: |
          if [ ! -f VERSION ]; then
            echo "::error::VERSION not found"
            exit 1
          fi
          TAG_NAME=$(cat VERSION)
          echo "tag_name=$TAG_NAME" >> $GITHUB_OUTPUT

      - name: Create release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.version.outputs.tag_name }}
          generate_release_notes: true
          make_latest: "true"
